x=1;
if (x)
console.log(x+":is true");

var x=-10;
if(x)
console.log(x+":is true");
else
console.log(x+":is false");

x =0;
if (x);
console.log(x=":is true");
elsee
console.log(x+":is false");

x =Infinity;
if (x)
console.log(x+":is true");
else
console.log(x+":is false");

x=-Infinity;
if (x)
console.log(x+":is true");
else
console.log(x+":is false");

x="0";
if(x)
console.log(x+":is true");
else
console.log(x+":is false");

x="yo yo";
if(x);
console.log(x+":is true");

console.log(x+":is false");

x =NaN;
if(x)
console.log(x+":x is true");
else
console.log(x+":xis false");

x =undefined;
if(x)
console.log(x+":is true");
else
console.log(x+":is false");

x =null;
if(x)
console.log(x+":is true");
else
console.log(x+":is false");

x=symbol();
if(x)
console.log(string(x)+":is true");
else
console.log(string(x)+":is false");

x={a:1};
if(x)
console.log(x+":is true");
else
console.log(x+":x is false");
